### PR TITLE
Better README, flameprof for profiling, scripts cleanup

### LINKED ISSUE #303: Clarify more dependencies needed to run the git version on Ubuntu and Debian
Hello there,

I've decided to contribute by testing the version from git (until now I've being using intensively the Debian package, version 0.3.1). My operating system is Tails (https://tails.boum.org), based on debian Buster

I followed the instructions from README.md : 

```
$ git clone https://github.com/getting-things-gnome/gtg.git
$ cd gtg
# apt install python3-pip
# apt install python3-nose python3-xdg python3-pyflakes python3-pep8 python3-pycodestyle python3-mock python3-dbus gobject-introspection 
```
Runs smoothly
Unfortunatelly, this last step brings the following errors : 

**$ torify pip3 install -r requirements.txt**

```
Requirement already satisfied: nose in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (1.3.7)
Collecting spec (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/fa/73/efc20b115cb391e89c9e4902a56ba5d0e244feb306e567383ab9b8ff72ab/spec-1.4.1-py2.py3-none-any.whl
Requirement already satisfied: pyxdg in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (0.25)
Requirement already satisfied: pyflakes in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (2.0.0)
Requirement already satisfied: pep8 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.7.1)
Requirement already satisfied: pycodestyle in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (2.4.0)
Requirement already satisfied: mock in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7)) (2.0.0)
Obtaining liblarch from git+http://github.com/getting-things-gnome/liblarch.git#egg=liblarch (from -r requirements.txt (line 8))
  Updating ./src/liblarch clone
Collecting dbus-python (from -r requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/62/7e/d4fb56a1695fa65da0c8d3071855fa5408447b913c58c01933c2f81a269a/dbus-python-1.2.16.tar.gz (576kB)
    100% |████████████████████████████████| 583kB 124kB/s 
Requirement already satisfied: PyGObject in /usr/lib/python3/dist-packages (from -r requirements.txt (line 10)) (3.30.4)
Requirement already satisfied: six<2.0 in /usr/lib/python3/dist-packages (from spec->-r requirements.txt (line 2)) (1.12.0)
Requirement already satisfied: pycairo>=1.11.1 in /usr/lib/python3/dist-packages (from PyGObject->-r requirements.txt (line 10)) (1.16.2)
Building wheels for collected packages: dbus-python
  Running setup.py bdist_wheel for dbus-python ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vccypz6s/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-97usu3z4 --python-tag cp37:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for dbus-python
  Running setup.py clean for dbus-python
Failed to build dbus-python
Installing collected packages: spec, liblarch, dbus-python
  The script spec is installed in '/home/amnesia/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Running setup.py develop for liblarch
  Running setup.py install for dbus-python ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vccypz6s/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kzt63hfs/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    creating /tmp/pip-install-vccypz6s/dbus-python/build
    creating /tmp/pip-install-vccypz6s/dbus-python/build/temp.linux-x86_64-3.7
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
[...] 
    checking python extra linking flags... -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions
    checking consistency of all components of python development environment... no
    configure: error: in `/tmp/pip-install-vccypz6s/dbus-python/build/temp.linux-x86_64-3.7':
    configure: error:
      Could not link test program to Python. Maybe the main Python library has been
      installed in some non-standard library path. If so, pass it to configure,
      via the LIBS environment variable.
      Example: ./configure LIBS="-L/usr/non-standard-path/python/lib"
      ============================================================================
       ERROR!
       You probably have to install the development version of the Python package
       for your distribution.  The exact name of this package varies among them.
      ============================================================================
    
    See `config.log' for more details
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vccypz6s/dbus-python/setup.py", line 111, in <module>
        tests_require=['tap.py'],
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-vccypz6s/dbus-python/setup.py", line 64, in run
        cwd=builddir)
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-vccypz6s/dbus-python/configure', '--disable-maintainer-mode', 'PYTHON=/usr/bin/python3', '--prefix=/tmp/pip-install-vccypz6s/dbus-python/build/temp.linux-x86_64-3.7/prefix']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-vccypz6s/dbus-python/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kzt63hfs/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-install-vccypz6s/dbus-python/

```

It does not prevent GTG form starting, but I stumbled upon other bugs and I would like to start on good bases.

Do you have any hint?

BTW, I'm really glad to see this project revival!
Thank you, cheers

### LINKED ISSUE #535: Document some debugging and sample data testing tricks from the launch script
I've had this sitting in my personal todo list for way too long, and while it's easy to do, it requires taking the time to sit down and actually do it, so filing it here in case someone (maybe @vansia43? :) wants to beat me to the punch.

--------

launch.sh is a shortcut to [scripts/debug.sh](https://github.com/getting-things-gnome/gtg/blob/master/scripts/debug.sh), and as you can see it accepts a few options such as -d and -s, and I think it would be nice to clearly document those for new contributors:

* "-d" = debug mode, which prints a lot more information in the terminal about what is going on; we should encourage contributors to use proper debug statements like that instead of python's "print" function, this is much cleaner and lets people have access to that information if they turn on debugging, instead of everybody "temporarily" adding print statements all over the place "but not committing them to the code in git" and then everybody else needing to add those statements back to the code on their own... We had a similar system implemented in Pitivi, but it was probably more complex because it was also accessible from environment variables to be compatible with debugging GStreamer at the same time in a sychronized manner, and I had [documented that over there](http://developer.pitivi.org/Bug_reporting.html?gi-language=undefined#debug-logs) (GTG's case is probably much simpler, I'm not even sure if we have multiple debug severity "levels")
* -s = dataset to use; the git version of GTG provides the sample "screenshots" and "bryce" datasets. The anonymized "bryce" dataset is great for testing performance issues because it has nearly a thousand tasks. It's also a very old data set (circa 2009) that uses the original file format, so probably interesting on that front too to test potential file format migration issues...

For example launching with both options could be `./launch.sh -d -s "bryce"`; and it is possible to also enable the [GTK Inspector](https://wiki.gnome.org/Projects/GTK/Inspector) at the same time, so `GTK_DEBUG=interactive ./launch.sh -d -s "bryce"`

Maybe @neui would have tricks to add wrt profiling, too?

In the scripts directory there is also the script that was used to anonymize data that users can submit for testing purposes, which I suppose is where the "bryce" dataset came from. I suppose that's potentially worth mentioning somewhere for testers.

So yeah... probably worth documenting in the contributors' documentation files, and potentially even in the README, dunno. I'll let whoever tackles this evaluate where and how best to explain all these things :)

### LINKED ISSUE #538: Installing from Git on Debian 10 requires meson from buster-backports
Hi there,

I finally managed to install GTG from Git on Debian 10!

The documentation is straight-forward, except one step, the installation of `meson`: if the installation is done with `apt install meson` the version installed on Debian 10 is `meson 0.49.2-1` and the following error appears when launching `./launch.sh`

`meson.build:1:0: ERROR:  Meson version is 0.49.2 but project requires >= 0.51.0.`

The solution is to install it from `debian-backports`:

`apt install -t buster-backports meson`

See [the doc on Debian.org](https://backports.debian.org/Instructions/) to add the backports to your repositories

### PR DESCRIPTION
**Pull request by Neui**
Look into the commits for a bit more info.
I'll probably improve it a bit, and needs testing.

Fixes #535
"Fixes" #321 by simply removing the option since it is too specialized and you probably could just set `PYTHONPATH` (untested)
Fixes #538 but not tested (not sure if you need to use `-t buster-backports`)
Maybe fixes #303, also needs testing

### CODE REVIEW

File: scripts/import_tasks_from_local.sh [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+mkdir -p tmp/default/xdg/data/gtg/
+mkdir -p tmp/default/xdg/config/gtg/
+
+cp -Rf ~/.local/share/gtg/* tmp/default/xdg/data/gtg/
+cp -Rf ~/.config/gtg/* tmp/default/xdg/config/gtg/
+
+test -f tmp/default/xdg/data/gtg/projects.xml && \
+    sed -i -e 's_\/home\/.*\/\.local\/share_tmp\/default\/xdg\/data_' tmp/default/xdg/data/gtg/projects.xml
+
+rm -f tmp/default/xdg/data/gtg/gtg.pid # Remove PID file protection
```
Comment (diegogangl) [inline scripts/import_tasks_from_local.sh:17]: We don't have PID protection files anymore

Comment (Neui) [reply scripts/import_tasks_from_local.sh:17]: It was there before, so I kept it. It would also clean up just in case the user had for some reason an old stale pid file, making the directory ever a bit cleaner, and it doesn't hurt (no error when the file is missing)

**Comment by diegogangl** [comment]
Ah ok, sounds good then. Thanks!

**Comment by Neui** [comment]
But I haven't actually tested everything yet...

**Comment by diegogangl** [comment]
>_>
LOL, well I guess we'll be testing in master then!
